### ISSUE TITLE
How to add a full node?

### ISSUE THREAD

**Issue by antonio-altr** [OffchainLabs/nitro-testnode#19]
I'd like to test adding a full node to this local nitro testing setup, but I'm getting an error when launching it.

Steps (on Ubuntu):
1. Launch the local testing setup (using latest nitro release, no stylus)
2. Create a node config file for the full node (taking reference from the sequencer's config file): [nodeconfig-fullnode.json](https://github.com/OffchainLabs/nitro-testnode/files/13295763/nodeconfig-fullnode.json)
3. Launch the full node:
   ```
   docker run --rm \
       -v /home/ubuntu/nodeconfig-fullnode.json:/home/user/config.json \
       -p 0.0.0.0:8123:8449 \
       offchainlabs/nitro-node:v2.1.1-e9d8842 \
       --conf.file=/home/user/config.json
   ```
4. Result:
   ```
   WARN [11-08|10:55:03.494] Chain information parentChainIsArbitrum field missing, in the future this will be required chainId=412,346 parentChainId=1337
   INFO [11-08|10:55:03.504] created jwt file                         filename=/home/user/.arbitrum/jwtsecret
   INFO [11-08|10:55:03.504] Running Arbitrum nitro node              revision=v2.1.1-e9d8842 vcs.time=2023-09-29T23:06:48-07:00
   CRIT [11-08|10:56:03.504] couldn't connect to L1                   err="timeout trying to connect lastError: dial tcp: lookup geth on 172.31.0.2:53: no such host"
   ```

`parent-chain.connection.url` is copied from the sequencer container, so I'm not sure why this error appears when launching the full node.

If you folks can spot what's wrong with my setup, or if you can propose a more correct way to set up the full node, I'd appreciate the help. Thanks!

**Comment by joshuacolvin0** [comment]
Any questions about running a node should be directed to Discord channel.  Thanks!
