### ISSUE TITLE
Is there a way to simplify and speed up the localnet development?

### ISSUE THREAD

**Issue by ahasna** [OffchainLabs/nitro-testnode#4]
Hey! 
I am trying to setup a Arbitrum testnet environment in CI. 
Ai was able to follow the README and get things going locally and deploy some contracts of both L1 and L2 successfully. However, when I attempt to "freeze" my setup, by executing `docker commit` to make it easier and faster to transfer to other devs, I start hitting all sorts of errors.

Is there a way to make the setup time faster and/or preserving some initial state for running a local network?

**Comment by tsahee** [comment]
Hello!
Sorry for the very long delay. We've just updated nitro-testnode to by default use "simple-mode". In this mode, there is only one l2node present which does sequencing, batch posting, and staking.
This should allow stopping with "docker-compose stop" and restarting with either docker-compose or testnode bash.

**Comment by ChichazzZ** [comment]
> Hello! Sorry for the very long delay. We've just updated nitro-testnode to by default use "simple-mode". In this mode, there is only one l2node present which does sequencing, batch posting, and staking. This should allow stopping with "docker-compose stop" and restarting with either docker-compose or testnode bash.

Hello, I am new to development in this area. I encountered an error when running the command `./test-node.bash --init` error: error Command "create-rollup-testnode" not found. Source: https://docs.arbitrum.io/run-arbitrum-node/run-local-dev-node.
I would like to know if this error will affect subsequent running nodes? and how to solve this problem. Also, nitro-testnode-sequencer-1 is not found in my docker image. What is the reason and how to solve it? And in nitro-testnode/scripts/config.ts, line 257, there is no "sequencer_config.json" file. These trouble me as a newbie. Hope to get your answer, thank you very much!
![error](https://github.com/OffchainLabs/nitro-testnode/assets/116890764/c37af537-b29c-45fe-a023-3839c723a0b8)
