### ISSUE TITLE
Devnet creation failled

### ISSUE THREAD

**Issue by RenanSouza2** [OffchainLabs/nitro-testnode#91]
When I run `./test-node.bash --init` it fails

`
Error: missing response (requestBody="{\"method\":\"eth_syncing\",\"params\":[],\"id\":42,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"172.19.0.2","port":8545}, url="http://geth:8545", code=SERVER_ERROR, version=web/5.6.0)
    at Logger.makeError (/workspace/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/workspace/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at /workspace/node_modules/@ethersproject/web/lib/index.js:252:36
    at step (/workspace/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.throw (/workspace/node_modules/@ethersproject/web/lib/index.js:14:53)
    at rejected (/workspace/node_modules/@ethersproject/web/lib/index.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'missing response',
  code: 'SERVER_ERROR',
  requestBody: '{"method":"eth_syncing","params":[],"id":42,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  serverError: Error: connect ECONNREFUSED 172.19.0.2:8545
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.19.0.2',
    port: 8545
  },
  url: 'http://geth:8545'
}
`

**Comment by RenanSouza2** [comment]
WHay may be related

`
INFO [10-07|22:57:32.214] Maximum peer count                       ETH=50 total=50
INFO [10-07|22:57:32.215] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [10-07|22:57:32.218] Set global gas cap                       cap=50,000,000
INFO [10-07|22:57:32.218] Initializing the KZG library             backend=gokzg
INFO [10-07|22:57:32.233] Defaulting to pebble as the backing database
INFO [10-07|22:57:32.233] Allocated cache and file handles         database=/datadir/geth/chaindata cache=16.00MiB handles=16
INFO [10-07|22:57:33.088] Opened ancient database                  database=/datadir/geth/chaindata/ancient/chain readonly=false
ERROR[10-07|22:57:33.088] Head block is not reachable
INFO [10-07|22:57:33.088] State scheme set by user                 scheme=hash
INFO [10-07|22:57:33.088] Writing custom genesis block
INFO [10-07|22:57:33.210] Persisted trie from memory database      nodes=35 size=5.10KiB time=68.585356ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=0 livesize=0.00B
INFO [10-07|22:57:33.798] Successfully wrote genesis state         database=chaindata                             hash=2dfffa..55cbdf
`

**Comment by joshuacolvin0** [comment]
`Smartcard socket not found` is an expected warning from go-ethereum, doesn't cause any problems.

Sounds like an error in the docker compose.  I would recommend using https://github.com/OffchainLabs/nitro-devnode for a simpler setup.

If you need further help, asking questions on our Discord server is better for questions running node.
